(()=>{const KEY='mi-entrenamiento-v2-data',M=['Pecho','Espalda','Hombros','Bíceps','Tríceps','Cuádriceps','Isquios','Glúteos','Pantorrillas','Abdomen','Otro'];const DEF=[['Press banca','Pecho'],['Press inclinado con mancuernas','Pecho'],['Flexiones','Pecho'],['Remo con mancuerna','Espalda'],['Dominadas','Espalda'],['Jalón al pecho','Espalda'],['Press militar','Hombros'],['Elevaciones laterales','Hombros'],['Curl de bíceps','Bíceps'],['Curl martillo','Bíceps'],['Extensión de tríceps','Tríceps'],['Fondos','Tríceps'],['Sentadilla','Cuádriceps'],['Prensa','Cuádriceps'],['Peso muerto rumano','Isquios'],['Curl femoral','Isquios'],['Hip thrust','Glúteos'],['Elevación de gemelos','Pantorrillas'],['Plancha','Abdomen'],['Crunch','Abdomen']];let S=(()=>{try{let x=JSON.parse(localStorage.getItem(KEY));if(x)return x}catch{}return{entries:[],exercises:DEF.map(x=>({name:x[0],muscle:x[1]})),goals:[]}})(),cal=new Date(),period=7,selected=iso(new Date()),deferred=null,timer={s:90,total:90,run:false,id:null};const $=x=>document.getElementById(x),pad=n=>String(n).padStart(2,'0'),iso=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,TOD=iso(new Date()),esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])),entries=d=>S.entries.filter(x=>x.date===d),sets=e=>e.reduce((a,x)=>a+x.sets.length,0),vol=e=>e.reduce((a,x)=>a+x.sets.reduce((b,s)=>b+(+s.weight||0)*(+s.reps||0),0),0),save=()=>localStorage.setItem(KEY,JSON.stringify(S));
function dateText(d){return new Date(d+'T12:00:00').toLocaleDateString('es-CL',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}function short(d){return new Date(d+'T12:00:00').toLocaleDateString('es-CL',{day:'numeric',month:'short'})}function ago(n){let d=new Date();d.setDate(d.getDate()-n);return iso(d)}
function render(){renderToday();renderHistory();renderCalendar();renderStats();renderGoals();$('dateNow').textContent=new Date().toLocaleDateString('es-CL',{day:'numeric',month:'long',year:'numeric'})}
function renderToday(){let e=entries(TOD);$('todayTitle').textContent=new Date().toLocaleDateString('es-CL',{weekday:'long',day:'numeric',month:'long'});$('todaySub').textContent=e.length?`${e.length} ejercicios · ${sets(e)} series · ${Math.round(vol(e)).toLocaleString('es-CL')} kg`:'Listo para entrenar';$('tEx').textContent=e.length;$('tSets').textContent=sets(e);$('tVol').textContent=Math.round(vol(e)).toLocaleString('es-CL')+' kg';$('todayEmpty').style.display=e.length?'none':'block';$('todayList').innerHTML=e.map(ex=>`<div class="exercise"><div class="exerciseTop"><div><h3>${esc(ex.name)}</h3><small>${esc(ex.muscle)}${ex.notes?' · '+esc(ex.notes):''}</small></div><button class="delete" data-del="${ex.id}">Eliminar</button></div><div class="sets"><div class="set muted"><span>#</span><span>kg</span><span>reps</span><span>RIR</span><span></span></div>${ex.sets.map((s,i)=>`<div class="set"><span>${i+1}</span><input data-e="${ex.id}" data-i="${i}" data-f="weight" type="number" step=".5" value="${s.weight}"><input data-e="${ex.id}" data-i="${i}" data-f="reps" type="number" value="${s.reps}"><input data-e="${ex.id}" data-i="${i}" data-f="rir" type="number" min="0" max="10" value="${s.rir||0}"><button class="delete" data-set="${ex.id}|${i}">×</button></div>`).join('')}</div><button class="link" data-addset="${ex.id}">＋ Añadir serie</button></div>`).join('');document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{S.entries=S.entries.filter(x=>x.id!=b.dataset.del);save();render()});document.querySelectorAll('[data-set]').forEach(b=>b.onclick=()=>{let [id,i]=b.dataset.set.split('|'),e=S.entries.find(x=>x.id==id);e.sets.splice(+i,1);save();render()});document.querySelectorAll('[data-addset]').forEach(b=>b.onclick=()=>{let e=S.entries.find(x=>x.id==b.dataset.addset),last=e.sets[e.sets.length-1]||{weight:0,reps:10,rir:2};e.sets.push({...last});save();render()});document.querySelectorAll('[data-f]').forEach(i=>i.onchange=()=>{let e=S.entries.find(x=>x.id==i.dataset.e);e.sets[+i.dataset.i][i.dataset.f]=+i.value||0;save();renderToday()})}
function modal(h){$('modalBody').innerHTML=h;$('modal').classList.remove('hidden')}function close(){ $('modal').classList.add('hidden')}
function addExercise(){let opts=S.exercises.map((e,i)=>`<option value="${i}">${esc(e.name)} — ${esc(e.muscle)}</option>`).join('');modal(`<h2>Registrar ejercicio</h2><div class="form"><label class="full">Ejercicio<select id="exSel">${opts}</select></label><label>Series<input id="nSet" type="number" min="1" value="3"></label><label>Reps<input id="nRep" type="number" min="1" value="10"></label><label>Peso inicial (kg)<input id="nW" type="number" min="0" step=".5" value="0"></label><label>RIR<input id="nR" type="number" min="0" max="10" value="2"></label><label class="full">Notas<textarea id="nNote"></textarea></label></div><div class="actions"><button class="secondary" id="cancel">Cancelar</button><button class="primary" id="saveEx">Guardar</button></div>`);$('cancel').onclick=close;$('saveEx').onclick=()=>{let x=S.exercises[+$('exSel').value],n=Math.max(1,+$('nSet').value||1),r=+$('nRep').value||0,w=+$('nW').value||0,ri=+$('nR').value||0;S.entries.push({id:Date.now(),date:TOD,name:x.name,muscle:x.muscle,notes:$('nNote').value,sets:Array.from({length:n},()=>({weight:w,reps:r,rir:ri}))});save();close();render()}}
function renderHistory(){let ms=[...new Set(S.entries.map(x=>x.date.slice(0,7)))];if(!ms.includes(TOD.slice(0,7)))ms.unshift(TOD.slice(0,7));let hm=$('histMonth'),old=hm.value;hm.innerHTML=ms.map(m=>`<option value="${m}">${new Date(m+'-01T12:00:00').toLocaleDateString('es-CL',{month:'long',year:'numeric'})}</option>`).join('');hm.value=ms.includes(old)?old:ms[0];let mu=$('histMuscle'),mv=mu.value;mu.innerHTML='<option value="">Todos los músculos</option>'+M.map(x=>`<option>${x}</option>`).join('');mu.value=mv;let es=S.entries.filter(x=>x.date.startsWith(hm.value)&&(!mu.value||x.muscle===mu.value)),ds=[...new Set(es.map(x=>x.date))].sort().reverse();$('historyList').innerHTML=ds.length?ds.map(d=>`<div class="dayGroup"><h3>${dateText(d)}</h3>${es.filter(x=>x.date===d).map(x=>`<div class="historyRow"><span><b>${esc(x.name)}</b><small> · ${x.sets.length} series · ${esc(x.muscle)}</small></span><span>${Math.round(vol([x])).toLocaleString('es-CL')} kg</span></div>`).join('')}</div>`).join(''):'<div class="empty">No hay datos para este filtro.</div>'}
function renderCalendar(){let y=cal.getFullYear(),m=cal.getMonth(),f=new Date(y,m,1),days=new Date(y,m+1,0).getDate(),off=(f.getDay()+6)%7;$('calTitle').textContent=f.toLocaleDateString('es-CL',{month:'long',year:'numeric'});let h=''.padStart(off,'<span></span>');for(let d=1;d<=days;d++){let k=`${y}-${pad(m+1)}-${pad(d)}`,has=entries(k).length;h+=`<button class="${has?'trained ':''}${k===selected?'selected':''}" data-day="${k}">${d}${has?'<i class="dot"></i>':''}</button>`}$('calGrid').innerHTML=h;document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{selected=b.dataset.day;renderCalendar()});let e=entries(selected);$('dayDetail').innerHTML=`<div class="head"><h3>${dateText(selected)}</h3></div>${e.length?e.map(x=>`<div class="historyRow"><b>${esc(x.name)}</b><span>${x.sets.length} series · ${Math.round(vol([x]))} kg</span></div>`).join(''):'<div class="empty">No hay ejercicios registrados.</div>'}`}
function periodEntries(){if(period==='all')return S.entries;return S.entries.filter(x=>x.date>=ago(period-1))}
function chartLine(id,labels,values){let c=$(id),ctx=c.getContext('2d'),w=c.clientWidth||600,h=230,d=devicePixelRatio||1;c.width=w*d;c.height=h*d;ctx.scale(d,d);ctx.clearRect(0,0,w,h);if(!values.length)return;let max=Math.max(...values,1),px=30,pw=w-45,ph=175,py=18;ctx.strokeStyle='#e2e6ec';for(let i=0;i<4;i++){let y=py+i*ph/3;ctx.beginPath();ctx.moveTo(px,y);ctx.lineTo(w-12,y);ctx.stroke()}ctx.beginPath();values.forEach((v,i)=>{let x=px+(values.length<2?pw/2:pw*i/(values.length-1)),y=py+ph-v/max*ph;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.strokeStyle='#111827';ctx.lineWidth=3;ctx.stroke();ctx.fillStyle='#6f7b8f';ctx.font='11px system-ui';[0,Math.floor((labels.length-1)/2),labels.length-1].filter((x,i,a)=>x>=0&&a.indexOf(x)===i).forEach(i=>ctx.fillText(labels[i],Math.max(2,px+pw*(labels.length<2?.5:i/(labels.length-1))-20),215))}
function chartBars(id,data){let c=$(id),ctx=c.getContext('2d'),w=c.clientWidth||600,h=230,d=devicePixelRatio||1;c.width=w*d;c.height=h*d;ctx.scale(d,d);ctx.clearRect(0,0,w,h);if(!data.length)return;let max=Math.max(...data.map(x=>x.v),1),bw=(w-35)/data.length-8;data.forEach((x,i)=>{let bh=x.v/max*175,xx=20+i*((w-25)/data.length),yy=195-bh;ctx.fillStyle='#111827';ctx.fillRect(xx,yy,bw,bh);ctx.fillStyle='#68748a';ctx.font='10px system-ui';ctx.textAlign='center';ctx.fillText(x.k,xx+bw/2,214);ctx.fillText(Math.round(x.v),xx+bw/2,yy-4)})}
function renderStats(){let es=periodEntries();$('sDays').textContent=new Set(es.map(x=>x.date)).size;$('sSets').textContent=sets(es);$('sVol').textContent=Math.round(vol(es)).toLocaleString('es-CL')+' kg';$('sExercises').textContent=es.length;let n=period==='all'?30:+period,lab=[],val=[];for(let i=n-1;i>=0;i--){let d=ago(i);lab.push(short(d));val.push(vol(entries(d)))}chartLine('volumeChart',lab,val);let map={};es.forEach(e=>map[e.muscle]=(map[e.muscle]||0)+e.sets.length);chartBars('muscleChart',Object.entries(map).sort((a,b)=>b[1]-a[1]).map(x=>({k:x[0],v:x[1]})));let pe=$('progEx'),names=[...new Set(S.entries.map(x=>x.name))],old=pe.value;pe.innerHTML=names.map(x=>`<option>${esc(x)}</option>`).join('')||'<option>Sin datos</option>';if(names.includes(old))pe.value=old;let g={};S.entries.filter(x=>x.name===pe.value).forEach(e=>e.sets.forEach(s=>g[e.date]=Math.max(g[e.date]||0,(+s.weight||0)*(1+(+s.reps||0)/30))));let pts=Object.entries(g).sort();chartLine('progressChart',pts.map(x=>short(x[0])),pts.map(x=>x[1]));let now=S.entries.filter(x=>x.date>=ago(6)),prev=S.entries.filter(x=>x.date>=ago(13)&&x.date<ago(6));let rows=[['Días',new Set(now.map(x=>x.date)).size,new Set(prev.map(x=>x.date)).size],['Series',sets(now),sets(prev)],['Volumen',Math.round(vol(now)),Math.round(vol(prev))]];$('compare').innerHTML=rows.map(r=>{let p=r[2]?Math.round((r[1]-r[2])/r[2]*100):r[1]?100:0;return `<div class="compare"><span>${r[0]}</span><b>${r[1]}</b><span class="${p>=0?'up':'down'}">${p>=0?'+':''}${p}%</span></div>`}).join('');let best={};S.entries.forEach(e=>e.sets.forEach(s=>{let est=(+s.weight||0)*(1+(+s.reps||0)/30);if(!best[e.name]||est>best[e.name].est)best[e.name]={w:+s.weight||0,r:+s.reps||0,est}}));let rec=Object.entries(best).sort((a,b)=>b[1].est-a[1].est);$('records').innerHTML=rec.length?rec.map(x=>`<div class="record"><span><b>${esc(x[0])}</b><small> · mejor estimación</small></span><span><strong>${x[1].w} kg</strong> × ${x[1].r}</span></div>`).join(''):'<small class="muted">Aún no hay récords.</small>'}

function renderBody(){
 const es=periodEntries(bodyPeriod), counts={};MUSCLES.forEach(m=>counts[m]=0);
 es.forEach(e=>{counts[e.muscle]=(counts[e.muscle]||0)+e.sets.length});
 let max=Math.max(...Object.values(counts),1);
 document.querySelectorAll(".body-figure .muscle").forEach(el=>{
   let m=el.dataset.muscle,n=counts[m]||0,ratio=n/max,level=n===0?0:ratio<.25?1:ratio<.5?2:ratio<.8?3:4;
   el.setAttribute("class",`muscle ${level?"level-"+level:""}`);
 });
 const target=10;
 document.getElementById("muscleStatus").innerHTML=MUSCLES.filter(m=>m!=="Otro").map(m=>{
   let n=counts[m]||0,level=n===0?"Sin series registradas":n<4?"Volumen bajo":n<target?"Volumen moderado":"Buen volumen registrado";
   let hint=n===0?"No hay trabajo registrado en este período.":n<4?"Revisa si este músculo recibe suficiente estímulo y esfuerzo.":n<target?"Puede ser suficiente según intensidad, experiencia y frecuencia.":"Evalúa recuperación y progreso antes de añadir más.";
   return `<div class="muscle-status-row"><div><b>${esc(m)}</b><small>${hint}</small></div><strong>${n} series<br>${level}</strong></div>`;
 }).join("");
}
function setupReminders(){
 showModal(`<h2>Recordatorio de entrenamiento</h2><p class="muted">Los recordatorios web dependen del navegador y del sistema; no siempre aparecen si el navegador está cerrado o el dispositivo limita la actividad.</p><div class="form-grid"><div class="form-field"><label>Hora</label><input type="time" id="reminderTime" value="${localStorage.getItem("workout-reminder-time")||"18:00"}"></div><div class="form-field"><label>Días</label><select id="reminderDays"><option value="weekdays">Lunes a viernes</option><option value="all">Todos los días</option><option value="weekend">Fin de semana</option></select></div></div><div class="form-actions"><button class="secondary" id="disableReminder">Desactivar</button><button class="primary" id="saveReminder">Guardar</button></div>`);
 document.getElementById("saveReminder").onclick=async()=>{if(!("Notification" in window)){alert("Este navegador no admite notificaciones.");return;}let permission=Notification.permission;if(permission==="default")permission=await Notification.requestPermission();if(permission!=="granted"){alert("No se concedió permiso para notificaciones. Puedes activarlo en los ajustes del navegador.");return;}localStorage.setItem("workout-reminder-time",document.getElementById("reminderTime").value);localStorage.setItem("workout-reminder-days",document.getElementById("reminderDays").value);closeModal();toast("Preferencia guardada. La notificación depende del navegador.");};
 document.getElementById("disableReminder").onclick=()=>{localStorage.removeItem("workout-reminder-time");localStorage.removeItem("workout-reminder-days");closeModal();toast("Recordatorio desactivado");};
}
\nfunction renderGoals(){let el=$('goalList');if(!S.goals.length){el.innerHTML='<div class="empty">No tienes objetivos. Crea una meta medible.</div>';return}el.innerHTML=S.goals.map(g=>{let e=S.entries.filter(x=>(!g.start||x.date>=g.start)&&(!g.end||x.date<=g.end)),cur=g.type==='days'?new Set(e.map(x=>x.date)).size:g.type==='sets'?sets(e):g.type==='volume'?Math.round(vol(e)):e.reduce((a,x)=>a+x.sets.reduce((b,s)=>b+(+s.reps||0),0),0),p=Math.min(100,Math.round(cur/g.target*100));return `<div class="goal"><div class="goalTop"><b>${esc(g.title)}</b><button class="delete" data-goal="${g.id}">×</button></div><progress value="${p}" max="100"></progress><div><b>${cur}</b> / ${g.target} ${g.unit} · ${p}%</div><small>${esc(g.desc||'')}</small></div>`}).join('');document.querySelectorAll('[data-goal]').forEach(b=>b.onclick=()=>{S.goals=S.goals.filter(x=>x.id!=b.dataset.goal);save();renderGoals()})}
function goalModal(){modal(`<h2>Nueva meta</h2><div class="form"><label class="full">Nombre<input id="gt" placeholder="Entrenar 4 días"></label><label>Tipo<select id="gty"><option value="days">Días entrenados</option><option value="sets">Series</option><option value="volume">Volumen (kg)</option><option value="reps">Repeticiones</option></select></label><label>Objetivo<input id="gval" type="number" min="1" value="4"></label><label>Desde<input id="gs" type="date" value="${TOD}"></label><label>Hasta<input id="ge" type="date"></label><label class="full">Descripción<input id="gd"></label></div><div class="actions"><button class="secondary" id="gc">Cancelar</button><button class="primary" id="gok">Crear</button></div>`);$('gc').onclick=close;$('gok').onclick=()=>{let t=$('gty').value,u=t==='days'?'días':t==='sets'?'series':t==='volume'?'kg':'reps';S.goals.push({id:Date.now(),title:$('gt').value||'Mi objetivo',type:t,target:+$('gval').value||1,unit:u,start:$('gs').value,end:$('ge').value,desc:$('gd').value});save();close();renderGoals()}}
function manage(){modal(`<h2>Ejercicios</h2><div class="form"><label>Nombre<input id="en"></label><label>Músculo<select id="em">${M.map(x=>`<option>${x}</option>`).join('')}</select></label></div><div class="actions"><button class="primary" id="eok">Agregar</button></div><div>${S.exercises.map((x,i)=>`<div class="historyRow"><span>${esc(x.name)}<small> · ${x.muscle}</small></span>${i>=DEF.length?`<button class="delete" data-exdel="${i}">×</button>`:''}</div>`).join('')}</div>`);$('eok').onclick=()=>{let n=$('en').value.trim();if(n){S.exercises.push({name:n,muscle:$('em').value});save();manage()}};document.querySelectorAll('[data-exdel]').forEach(b=>b.onclick=()=>{S.exercises.splice(+b.dataset.exdel,1);save();manage()})}
function timerStart(s=90){clearInterval(timer.id);timer.s=timer.total=s;timer.run=true;$('timer').classList.remove('hidden');tick();timer.id=setInterval(()=>{if(timer.run){timer.s--;tick();if(timer.s<=0){clearInterval(timer.id);timer.run=false;navigator.vibrate?.([300,150,300])}}},1000)}function tick(){$('timerText').textContent=`${pad(Math.floor(timer.s/60))}:${pad(timer.s%60)}`;$('timerBar').style.width=(timer.s/timer.total*100)+'%';$('pause').textContent=timer.run?'Pausar':'Continuar'}
function exportData(){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(S,null,2)],{type:'application/json'}));a.download='mi-entrenamiento-respaldo-'+TOD+'.json';a.click()}function importData(f){let r=new FileReader;r.onload=()=>{try{let x=JSON.parse(r.result);if(!x.entries||!x.exercises)throw 0;S=x;save();render()}catch{alert('Respaldo no válido')}};r.readAsText(f)}
function go(v){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));$(v).classList.add('active');document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('active',x.dataset.v===v));if(v==='stats')renderStats()}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>go(b.dataset.v));$('add').onclick=addExercise;$('add2').onclick=addExercise;$('rest').onclick=()=>timerStart();$('close').onclick=close;$('prev').onclick=()=>{cal.setMonth(cal.getMonth()-1);renderCalendar()};$('next').onclick=()=>{cal.setMonth(cal.getMonth()+1);renderCalendar()};$('histMonth').onchange=renderHistory;$('histMuscle').onchange=renderHistory;$('progEx').onchange=renderStats;$('goalAdd').onclick=goalModal;$('exManage').onclick=manage;$('export').onclick=exportData;$('import').onclick=()=>$('file').click();$('file').onchange=e=>e.target.files[0]&&importData(e.target.files[0]);$('wipe').onclick=()=>{if(confirm('¿Borrar todos los datos?')){localStorage.removeItem(KEY);location.reload()}};document.querySelectorAll('.period button').forEach(b=>b.onclick=()=>{period=b.dataset.p;document.querySelectorAll('.period button').forEach(x=>x.classList.toggle('active',x===b));renderStats()});$('pause').onclick=()=>{timer.run=!timer.run;tick()};$('timerClose').onclick=()=>{$('timer').classList.add('hidden');clearInterval(timer.id)};document.querySelectorAll('[data-t]').forEach(b=>b.onclick=()=>timerStart(+b.dataset.t));window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;$('install').classList.remove('hidden')});$('install').onclick=async()=>{if(deferred){deferred.prompt();await deferred.userChoice;deferred=null;$('install').classList.add('hidden')}};if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});render()})();
